name: Update Submodules in Parent Repo

on:
  push:
    branches:
      - main  # develop

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout parent repository with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive  # garante que todos os submodules sejam clonados

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules to latest commits
        run: |
          # Inicializa e atualiza todos os submodules
          git submodule update --init --recursive

          # Array com os submodules que você quer atualizar
          for submodule in front-end back-end; do
            if [ -d "$submodule" ]; then
              echo "Updating $submodule..."
              cd $submodule
              git fetch --all
              git checkout ${{ github.sha }} || echo "Commit ${{ github.sha }} not found in $submodule"
              cd ..
              git add $submodule
            else
              echo "Submodule $submodule does not exist, skipping..."
            fi
          done

          # Commit se houver mudanças
          git diff --cached --quiet || git commit -m "chore: update submodules to latest commit ${{ github.sha }}"

          # Push para o branch
          git push origin develop
